# Generated by Django 4.1.1 on 2022-10-26 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="user", name="date_of_birth",),
    ]
